### PR TITLE
Pass by pointer for "Update" to ensure that internal state

### PR DESCRIPTION
**Pull request by jcscottiii**
If the state is change for route, we need to pass by pointer

### CODE REVIEW

**Comment by jmcarp** [comment]
Thanks for the fix! While we're at it, should we also change `Disable` and `Renew` to take a `*Route`?

**Comment by jcscottiii** [comment]
`Disable` needs it. For `Renew`, we don't.
Half of me is inclined to make all the calls to the manager which use Route to the pointer to be consistent / easy for other to come in and contribute. Thoughts? I can make the changes if you don't mind the bigger changeset for this PR
The other half of me is fine waiting until we get integration tests and just make the additional change for `Disable`

**Comment by jmcarp** [comment]
My (slight) preference is to make the signatures consistent now. If that sounds good, I'll get https://github.com/18F/cf-cdn-service-broker/pull/47 merged before merging this so that I can test on staging.

**Comment by jcscottiii** [comment]
sounds good! will make the changes!

**Comment by jcscottiii** [comment]
just a friendly bump on this :)

**Pull request merged**
