### PR TITLE
log provisioning/deprovisioning errors

### PR DESCRIPTION
**Pull request by cnelson**

### CODE REVIEW

**Comment by jmcarp** [comment]
Since we're already using `lager` for logging (since it's used in `brokerapi`), wdyt about adding `logger lager.Logger` to the `CdnServiceBroker` struct and using that to add the error log?

**Comment by cnelson** [comment]
I haven't used lager before, does that look right? ☝️

**Comment by jmcarp** [comment]
LGTM, I think we just need to pass the `logger` when instantiating the broker in https://github.com/18F/cf-cdn-service-broker/blob/master/cmd/cdn-broker/main.go#L47-L49.

**Comment by jmcarp** [comment]
Tests passing locally, LGTM.

**Pull request merged**
