### PR TITLE
[WIP] Support Multiple domains

### PR DESCRIPTION
**Pull request by dlapiduz**
The idea here is to allow users to pass a comma delimited string rather than just one domain.

### CODE REVIEW

**Comment by dlapiduz** [comment]
It resolves #20 20

**Comment by jmcarp** [comment]
Looks good. I was thinking of accepting `domains` as an actual json array, but this is simpler, so 👍. Can you add a multi-domain example to the readme also?

**Comment by dlapiduz** [comment]
I know json array makes sense but this was simpler :).

Added the instructions though.

**Comment by dlapiduz** [comment]
ok, this took actual work... thanks @jmcarp

**Pull request merged**
